//go:build !dot

package dashboard

import (
	"context"
	"encoding/json"
	"html"
	"math"
	"regexp"
	"strconv"
	"strings"
	"sync"

	"github.com/HuskerMinion/techo5/echod/internal/lib/hass"
)

// A dashboard of Home Assistant's own, drawn card by card. A sections view's sections, and a masonry
// view's cards, become the page's sections, laid out in columns the way Home Assistant lays them out.
// The cards people use most are drawn in the house's theme: tiles, cards of rows, headings, text,
// graphs, gauges and pictures. Stacks and grids are opened into the section they are in, and a card
// the device does not know is a tile that says what it is, so nothing silently goes missing.
//
// A dashboard Home Assistant generates for itself (the default Overview, until somebody takes it
// over) has no cards to read, and is drawn as the Rooms dashboard, which is what it would show.

type lovelaceSource struct {
	dashboard string // url_path; "lovelace" for the default
	view      string // a view's path or index; empty for the first

	// What was read, replaced whole under mu when it is read again: a rebuild from the connection
	// being replaced may still be running.
	mu       sync.Mutex
	sects    [][]node
	fallback *roomsSource
}

func newLovelace(path string) *lovelaceSource {
	dash, view, _ := strings.Cut(strings.Trim(path, "/"), "/")
	return &lovelaceSource{dashboard: dash, view: view}
}

func (l *lovelaceSource) load(ctx context.Context, live *hass.Live) (needs, error) {
	cmd := map[string]any{"type": "lovelace/config"}
	if l.dashboard != "" && l.dashboard != "lovelace" {
		cmd["url_path"] = l.dashboard
	}
	rawCfg, err := live.Call(ctx, cmd)
	if err != nil {
		return needs{}, onScreen("Home Assistant would not give this dashboard.")
	}
	var cfg struct {
		Views []raw `json:"views"`
	}
	if err := json.Unmarshal(rawCfg, &cfg); err != nil {
		return needs{}, err
	}
	if len(cfg.Views) == 0 {
		// Generated by Home Assistant: its areas are what it would show.
		fb := &roomsSource{}
		need, err := fb.load(ctx, live)
		l.mu.Lock()
		l.sects, l.fallback = nil, fb
		l.mu.Unlock()
		return need, err
	}
	view := cfg.Views[0]
	for i, v := range cfg.Views {
		if str(v, "path") == l.view || strconv.Itoa(i) == l.view {
			view = v
		}
	}

	c := &compiler{seen: map[string]bool{}, need: needs{graphs: map[string]int{}}}
	var sects [][]node
	if b := c.badges(view["badges"]); b != nil {
		sects = append(sects, []node{b})
	}
	if sections, ok := view["sections"].([]any); ok {
		for _, s := range sections {
			if sm, ok := s.(raw); ok {
				nodes := c.cards(sm["cards"])
				if len(nodes) == 0 {
					continue
				}
				if vis := c.conditions(sm["visibility"]); len(vis) > 0 {
					nodes = []node{condNode{conds: vis, child: group(nodes)}}
				}
				sects = append(sects, nodes)
			}
		}
	}
	// A masonry view: each card is a section of its own, and they flow into the columns.
	list, _ := view["cards"].([]any)
	for _, item := range list {
		if card, ok := item.(raw); ok {
			if n := c.card(card); n != nil {
				sects = append(sects, []node{n})
			}
		}
	}
	l.mu.Lock()
	l.sects, l.fallback = sects, nil
	l.mu.Unlock()
	return c.need, nil
}

func (l *lovelaceSource) sections(lk look) []Section {
	l.mu.Lock()
	sects, fallback := l.sects, l.fallback
	l.mu.Unlock()
	if fallback != nil {
		return fallback.sections(lk)
	}
	var out []Section
	for _, nodes := range sects {
		var blocks []Block
		for _, n := range nodes {
			blocks = append(blocks, n.blocks(lk)...)
		}
		// Tiles one after another make one grid, however many cards they came from: a section of
		// tile cards is one grid in Home Assistant too.
		var merged []Block
		for _, b := range blocks {
			if n := len(merged); n > 0 && onlyTiles(b) && onlyTiles(merged[n-1]) {
				merged[n-1].Tiles = append(merged[n-1].Tiles, b.Tiles...)
				continue
			}
			merged = append(merged, b)
		}
		if len(merged) > 0 {
			out = append(out, Section{Blocks: merged})
		}
	}
	return out
}

func onlyTiles(b Block) bool {
	return len(b.Tiles) > 0 && b.Heading == "" && b.Title == "" && len(b.Rows) == 0 && len(b.Text) == 0 &&
		b.Graph == nil && b.Gauge == nil && b.Picture == nil && len(b.Pictures) == 0
}

// node is a compiled card: what it draws from what has arrived.
type node interface {
	blocks(l look) []Block
}

type compiler struct {
	seen map[string]bool
	need needs
}

func (c *compiler) follow(entity string) {
	if entity != "" && !c.seen[entity] {
		c.seen[entity] = true
		c.need.entities = append(c.need.entities, entity)
	}
}

// render registers text for Home Assistant to render if it is a template, and says how to read it.
func (c *compiler) render(text, entity string) textRef {
	if !strings.Contains(text, "{{") && !strings.Contains(text, "{%") {
		return textRef{plain: text}
	}
	id := len(c.need.templates) + 1
	vars := map[string]any{}
	if entity != "" {
		vars["entity"] = entity
	}
	c.need.templates = append(c.need.templates, template{id: id, text: text, vars: vars})
	return textRef{template: id}
}

// textRef is words on the page: as written, or a template's latest rendering.
type textRef struct {
	plain    string
	template int
}

func (t textRef) get(rendered map[int]string) string {
	if t.template != 0 {
		return strings.TrimSpace(rendered[t.template])
	}
	return t.plain
}

func (c *compiler) cards(v any) []node {
	list, _ := v.([]any)
	var out []node
	for _, item := range list {
		if card, ok := item.(raw); ok {
			if n := c.card(card); n != nil {
				out = append(out, n)
			}
		}
	}
	return out
}

// entityCards are the cards that are one entity each, which become a tile.
var entityCards = map[string]bool{
	"tile": true, "button": true, "entity": true, "light": true, "thermostat": true, "humidifier": true,
	"media-control": true, "weather-forecast": true, "alarm-panel": true,
	"custom:mushroom-entity-card": true, "custom:mushroom-light-card": true, "custom:mushroom-climate-card": true,
	"custom:mushroom-cover-card": true, "custom:mushroom-fan-card": true, "custom:mushroom-media-player-card": true,
	"custom:mushroom-lock-card": true, "custom:mushroom-person-card": true, "custom:mushroom-alarm-control-panel-card": true,
	"custom:mushroom-select-card": true, "custom:mushroom-number-card": true, "custom:mushroom-vacuum-card": true,
	"custom:mushroom-humidifier-card": true, "custom:button-card": true, "custom:bubble-card": true,
	"custom:mini-media-player": true,
}

// graphCards draw their entities' history as lines.
var graphCards = map[string]bool{
	"history-graph": true, "statistics-graph": true, "custom:mini-graph-card": true, "custom:apexcharts-card": true,
}

// card compiles one card, behind its visibility conditions when it has any: Home Assistant hides a
// card whose conditions are not met, and so does the device.
func (c *compiler) card(card raw) node {
	n := c.cardItself(card)
	if n == nil {
		return nil
	}
	if vis := c.conditions(card["visibility"]); len(vis) > 0 {
		return condNode{conds: vis, child: n}
	}
	return n
}

func (c *compiler) cardItself(card raw) node {
	kind := str(card, "type")
	switch {
	case kind == "heading" || kind == "custom:mushroom-title-card":
		title := str(card, "heading")
		if title == "" {
			title = str(card, "title")
		}
		return headingNode{text: c.render(title, ""), sub: c.render(str(card, "subtitle"), "")}

	case kind == "markdown":
		return textNode{title: c.render(str(card, "title"), ""), body: c.render(str(card, "content"), "")}

	case kind == "entities":
		return c.rowsCard(card)

	case kind == "glance" || kind == "custom:mushroom-chips-card":
		key := "entities"
		if kind == "custom:mushroom-chips-card" {
			key = "chips"
		}
		n := listNode{title: c.render(str(card, "title"), "")}
		n.items = c.items(card[key])
		return n

	case kind == "custom:mushroom-template-card":
		e := str(card, "entity")
		c.follow(e)
		return templateNode{
			primary: c.render(str(card, "primary"), e), secondary: c.render(str(card, "secondary"), e),
			icon: c.render(str(card, "icon"), e), item: c.item(card, e),
		}

	case kind == "sensor":
		e := str(card, "entity")
		if e == "" {
			return nil
		}
		c.follow(e)
		if str(card, "graph") == "none" {
			return listNode{items: []tileItem{c.item(card, e)}}
		}
		hours := hoursOf(card, 24)
		c.need.graphs[e] = max(c.need.graphs[e], hours)
		return graphNode{entity: e, name: str(card, "name"), icon: str(card, "icon"), hours: hours}

	case graphCards[kind]:
		hours := hoursOf(card, 24)
		var g group
		for _, it := range c.items(card["entities"]) {
			if it.entity == "" {
				continue
			}
			c.need.graphs[it.entity] = max(c.need.graphs[it.entity], hours)
			g = append(g, graphNode{entity: it.entity, name: it.name, icon: it.icon, hours: hours})
		}
		if e := str(card, "entity"); e != "" && len(g) == 0 {
			c.follow(e)
			c.need.graphs[e] = max(c.need.graphs[e], hours)
			g = append(g, graphNode{entity: e, name: str(card, "name"), hours: hours})
		}
		if title := str(card, "title"); title != "" && len(g) > 0 {
			return group{headingNode{text: c.render(title, "")}, g}
		}
		return g

	case kind == "gauge":
		e := str(card, "entity")
		if e == "" {
			return nil
		}
		c.follow(e)
		n := gaugeNode{entity: e, name: str(card, "name"), min: 0, max: 100, unit: str(card, "unit")}
		if v, ok := card["min"].(float64); ok {
			n.min = v
		}
		if v, ok := card["max"].(float64); ok {
			n.max = v
		}
		if sev, ok := card["severity"].(raw); ok {
			n.severity = map[string]float64{}
			for k, v := range sev {
				if f, ok := v.(float64); ok {
					n.severity[k] = f
				}
			}
		}
		return n

	case kind == "picture-entity" || kind == "picture-glance" || kind == "picture" || kind == "picture-elements":
		w := wanted{camera: str(card, "camera_image"), url: str(card, "image")}
		e := str(card, "entity")
		if w.camera == "" && w.url == "" && strings.HasPrefix(e, "camera.") {
			w.camera = e
		}
		if w.camera == "" && w.url == "" {
			return nil
		}
		c.need.pictures = append(c.need.pictures, w)
		name := str(card, "title")
		if name == "" {
			name = str(card, "name")
		}
		return pictureNode{key: w.key(), name: name, tap: pictureTap(card, e)}

	case entityCards[kind]:
		e := str(card, "entity")
		if e == "" {
			// A button that only runs something: its name, its icon, what it runs.
			if a := actionOf(card, ""); a != nil {
				return listNode{items: []tileItem{{name: str(card, "name"), icon: str(card, "icon"), action: a, fixed: true}}}
			}
			return nil
		}
		c.follow(e)
		return listNode{items: []tileItem{c.item(card, e)}}

	case kind == "grid" || kind == "vertical-stack" || kind == "horizontal-stack" ||
		kind == "custom:stack-in-card" || kind == "custom:vertical-stack-in-card" || kind == "custom:layout-card":
		children := c.cards(card["cards"])
		if kind == "grid" {
			if g, ok := asGallery(children, card); ok {
				if title := str(card, "title"); title != "" {
					return group{headingNode{text: c.render(title, "")}, g}
				}
				return g
			}
		}
		inner := group(children)
		if title := str(card, "title"); title != "" {
			return group{headingNode{text: c.render(title, "")}, inner}
		}
		return inner

	case kind == "conditional":
		n := condNode{}
		if inner, ok := card["card"].(raw); ok {
			n.child = c.card(inner)
		}
		if n.child == nil {
			return nil
		}
		n.conds = c.conditions(card["conditions"])
		return n
	}
	if kind == "" {
		return nil
	}
	return listNode{items: []tileItem{{name: cardName(kind), icon: "card-outline", value: "Shown when streamed", fixed: true}}}
}

// rowsCard is an entities card: a card of rows, with any sections in it as headings of their own.
func (c *compiler) rowsCard(card raw) node {
	n := rowsNode{title: c.render(str(card, "title"), "")}
	list, _ := card["entities"].([]any)
	for _, it := range list {
		switch row := it.(type) {
		case string:
			c.follow(row)
			n.items = append(n.items, tileItem{entity: row})
		case raw:
			if str(row, "type") == "section" {
				n.items = append(n.items, tileItem{section: str(row, "label")})
				continue
			}
			if e := str(row, "entity"); e != "" {
				c.follow(e)
				n.items = append(n.items, c.item(row, e))
			}
		}
	}
	return n
}

// items are a card's entities, each a string or a map with its own name and icon.
func (c *compiler) items(v any) []tileItem {
	list, _ := v.([]any)
	var out []tileItem
	for _, it := range list {
		switch row := it.(type) {
		case string:
			c.follow(row)
			out = append(out, tileItem{entity: row})
		case raw:
			if e := str(row, "entity"); e != "" {
				c.follow(e)
				out = append(out, c.item(row, e))
			}
		}
	}
	return out
}

// item is an entity as a card or a row presents it: its own name and icon if it gives them, and its
// tap.
func (c *compiler) item(m raw, entity string) tileItem {
	return tileItem{entity: entity, name: str(m, "name"), icon: str(m, "icon"), action: actionOf(m, entity)}
}

func hoursOf(card raw, fallback int) int {
	if h, ok := card["hours_to_show"].(float64); ok && h > 0 {
		return int(math.Ceil(h))
	}
	if d, ok := card["days_to_show"].(float64); ok && d > 0 {
		return int(d * 24)
	}
	return fallback
}

// actionOf is a card's tap as a tile's action: nil for the default, which is the tile's own.
func actionOf(m raw, entity string) *Action {
	tap, _ := m["tap_action"].(raw)
	if tap == nil {
		return nil
	}
	switch str(tap, "action") {
	case "none":
		return &Action{}
	case "toggle":
		if entity == "" {
			return &Action{}
		}
		return &Action{Entity: entity, Service: "homeassistant.toggle"}
	case "call-service", "perform-action":
		service := str(tap, "perform_action")
		if service == "" {
			service = str(tap, "service")
		}
		data, _ := tap["data"].(raw)
		if data == nil {
			data, _ = tap["service_data"].(raw)
		}
		out := map[string]any{}
		for k, v := range data {
			out[k] = v
		}
		if target, ok := tap["target"].(raw); ok {
			for k, v := range target {
				out[k] = v
			}
		}
		return &Action{Entity: entity, Service: service, Data: out}
	case "navigate":
		return &Action{View: strings.Trim(str(tap, "navigation_path"), "/")}
	}
	return nil
}

func listOf(v any) []string {
	switch x := v.(type) {
	case string:
		return []string{x}
	case []any:
		var out []string
		for _, s := range x {
			if str, ok := s.(string); ok {
				out = append(out, str)
			}
		}
		return out
	}
	return nil
}

var customPrefix = regexp.MustCompile(`^custom:`)

// cardName is a card type as a person would say it: "custom:apexcharts-card" is "Apexcharts card".
func cardName(kind string) string {
	s := strings.ReplaceAll(customPrefix.ReplaceAllString(kind, ""), "-", " ")
	if s == "" {
		return "Card"
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// ---- the compiled cards --------------------------------------------------------------------------

type group []node

func (g group) blocks(l look) []Block {
	var out []Block
	for _, n := range g {
		out = append(out, n.blocks(l)...)
	}
	return out
}

type headingNode struct{ text, sub textRef }

func (h headingNode) blocks(l look) []Block {
	if t := h.text.get(l.rendered); t != "" {
		return []Block{{Heading: t, Right: h.sub.get(l.rendered)}}
	}
	return nil
}

type textNode struct{ title, body textRef }

func (t textNode) blocks(l look) []Block {
	b := Block{Title: t.title.get(l.rendered), Text: plainText(t.body.get(l.rendered))}
	if b.Title == "" && len(b.Text) == 0 {
		return nil
	}
	if len(b.Text) == 0 {
		b.Text = []string{""}
	}
	return []Block{b}
}

// tileItem is one tile or row a card asks for.
type tileItem struct {
	entity, name, icon, value string
	section                   string // a heading within a list instead
	action                    *Action
	fixed                     bool // not an entity's: drawn as given
}

// listNode is tiles.
type listNode struct {
	title textRef
	items []tileItem
}

func (n listNode) blocks(l look) []Block {
	var out []Block
	if t := n.title.get(l.rendered); t != "" {
		out = append(out, Block{Heading: t})
	}
	var tiles []Tile
	for _, it := range n.items {
		tiles = append(tiles, it.tile(l.states))
	}
	if len(tiles) > 0 {
		out = append(out, Block{Tiles: tiles})
	}
	return out
}

// rowsNode is an entities card: rows in a card, broken by its sections.
type rowsNode struct {
	title textRef
	items []tileItem
}

func (n rowsNode) blocks(l look) []Block {
	var out []Block
	cur := Block{Title: n.title.get(l.rendered)}
	for _, it := range n.items {
		if it.section != "" {
			if len(cur.Rows) > 0 || cur.Title != "" {
				out = append(out, cur)
			}
			cur = Block{Title: it.section}
			continue
		}
		t := it.tile(l.states)
		t.Switch = t.Tap != nil && strings.HasSuffix(t.Tap.Service, "toggle") && (t.Value == "On" || t.Value == "Off" || strings.HasPrefix(t.Value, "On ·"))
		cur.Rows = append(cur.Rows, t)
	}
	if len(cur.Rows) > 0 {
		out = append(out, cur)
	}
	return out
}

func (it tileItem) tile(states map[string]hass.LiveEntity) Tile {
	if it.fixed {
		return Tile{Name: it.name, Icon: orIcon(it.icon, "gesture-tap"), Value: it.value, Tap: it.action}
	}
	e, ok := states[it.entity]
	if !ok {
		e = hass.LiveEntity{ID: it.entity, State: "unknown", Attrs: map[string]any{}}
	}
	name := it.name
	if name == "" {
		name, _ = e.Attrs["friendly_name"].(string)
		if name == "" {
			name = it.entity
		}
	}
	t := describe(e, name)
	if it.icon != "" {
		t.Icon = it.icon
	}
	if it.action != nil {
		t.Tap = it.action
		if t.Tap.Service == "" && t.Tap.View == "" {
			t.Tap = nil // tap_action none
		}
	}
	return t
}

func orIcon(icon, fallback string) string {
	if icon == "" {
		return fallback
	}
	return icon
}

// templateNode is a Mushroom template card: its words and icon are templates.
type templateNode struct {
	primary, secondary, icon textRef
	item                     tileItem
}

func (t templateNode) blocks(l look) []Block {
	tile := Tile{Name: t.primary.get(l.rendered), Value: t.secondary.get(l.rendered), Icon: orIcon(t.icon.get(l.rendered), "card-text-outline")}
	if t.item.entity != "" {
		base := t.item.tile(l.states)
		tile.On, tile.Tap = base.On, base.Tap
	} else if t.item.action != nil && (t.item.action.Service != "" || t.item.action.View != "") {
		tile.Tap = t.item.action
	}
	if tile.Name == "" && tile.Value == "" {
		return nil
	}
	return []Block{{Tiles: []Tile{tile}}}
}

// graphNode is a sensor's history.
type graphNode struct {
	entity, name, icon string
	hours              int
}

// graphPoints is how many points a graph's line has across its card.
const graphPoints = 72

func (g graphNode) blocks(l look) []Block {
	e, ok := l.states[g.entity]
	if !ok {
		e = hass.LiveEntity{ID: g.entity, State: "unknown", Attrs: map[string]any{}}
	}
	name := g.name
	if name == "" {
		name, _ = e.Attrs["friendly_name"].(string)
	}
	t := describe(e, name)
	return []Block{{Graph: &Graph{Name: name, Icon: orIcon(g.icon, t.Icon), Value: t.Value, Points: buckets(l.history[g.entity], g.hours, graphPoints)}}}
}

// gaugeNode is a reading on an arc.
type gaugeNode struct {
	entity, name, unit string
	min, max           float64
	severity           map[string]float64
}

func (g gaugeNode) blocks(l look) []Block {
	e := l.states[g.entity]
	name := g.name
	if name == "" {
		name, _ = e.Attrs["friendly_name"].(string)
	}
	v, err := strconv.ParseFloat(e.State, 64)
	if err != nil {
		return []Block{{Gauge: &Gauge{Name: name, Value: title(e.State)}}}
	}
	unit := g.unit
	if unit == "" {
		unit, _ = e.Attrs["unit_of_measurement"].(string)
	}
	frac := 0.0
	if g.max > g.min {
		frac = min(max((v-g.min)/(g.max-g.min), 0), 1)
	}
	sev := ""
	best := math.Inf(-1)
	for _, k := range []string{"green", "yellow", "red"} {
		if at, ok := g.severity[k]; ok && v >= at && at > best {
			sev, best = k, at
		}
	}
	return []Block{{Gauge: &Gauge{Name: name, Value: strings.TrimSpace(trimNumber(v) + " " + unit), Frac: frac, Severity: sev}}}
}

// pictureNode is a camera or an image.
type pictureNode struct {
	key, name string
	tap       *Action
}

func (p pictureNode) picture(l look) Picture {
	img, arrived := l.pictures[p.key]
	return Picture{Name: p.name, Image: img, TooLarge: arrived && img == nil, Tap: p.tap}
}

func (p pictureNode) blocks(l look) []Block {
	pic := p.picture(l)
	return []Block{{Picture: &pic}}
}

// pictureTap is what a tap on a picture card does: its own tap_action, when that does something.
// Without one, or with "none" or "more-info", a picture stays something to look at, as before.
func pictureTap(card raw, entity string) *Action {
	a := actionOf(card, entity)
	if a == nil || (a.Service == "" && a.View == "") {
		return nil
	}
	return a
}

// galleryNode is a grid of nothing but pictures, drawn abreast rather than one under the other:
// a page of rooms, each a photo that opens it.
type galleryNode struct {
	pics    []pictureNode
	columns int
}

// asGallery is a grid's cards as a gallery, when the grid asks for two or more columns and every
// card in it is a picture. Anything else in it, and the grid stays as it was: its cards in turn.
func asGallery(children []node, card raw) (galleryNode, bool) {
	cols, _ := card["columns"].(float64)
	if cols < 2 || len(children) < 2 {
		return galleryNode{}, false
	}
	g := galleryNode{columns: int(cols)}
	for _, n := range children {
		p, ok := n.(pictureNode)
		if !ok {
			return galleryNode{}, false
		}
		g.pics = append(g.pics, p)
	}
	return g, true
}

func (g galleryNode) blocks(l look) []Block {
	b := Block{Columns: g.columns}
	for _, p := range g.pics {
		b.Pictures = append(b.Pictures, p.picture(l))
	}
	return []Block{b}
}

// cond is one of Home Assistant's conditions, as a conditional card and a card's visibility use
// them: an entity's state or number, the screen's width, or several of those together. A user
// condition is always met: the device is not signed in as anybody.
type cond struct {
	kind       string // state, numeric_state, screen, and, or, not, always
	entity     string
	state, not []string
	above      *float64
	below      *float64
	minW, maxW int // a screen condition's widths; 0 for no limit
	subs       []cond
}

// conditions reads a list of conditions, in either of the forms Home Assistant writes them: a
// conditional card's old {entity, state} or the {condition: ...} everything else uses.
func (c *compiler) conditions(v any) []cond {
	list, _ := v.([]any)
	var out []cond
	for _, x := range list {
		m, ok := x.(raw)
		if !ok {
			continue
		}
		kind := str(m, "condition")
		if kind == "" {
			kind = "state"
		}
		cd := cond{kind: kind}
		switch kind {
		case "state":
			cd.entity, cd.state, cd.not = str(m, "entity"), listOf(m["state"]), listOf(m["state_not"])
			if cd.entity == "" {
				continue
			}
			c.follow(cd.entity)
		case "numeric_state":
			cd.entity = str(m, "entity")
			if cd.entity == "" {
				continue
			}
			c.follow(cd.entity)
			if f, ok := number64(m["above"]); ok {
				cd.above = &f
			}
			if f, ok := number64(m["below"]); ok {
				cd.below = &f
			}
		case "screen":
			cd.minW, cd.maxW = widths(str(m, "media_query"))
		case "and", "or", "not":
			cd.subs = c.conditions(m["conditions"])
		default:
			cd.kind = "always" // user, location and the like: nothing here to hold against
		}
		out = append(out, cd)
	}
	return out
}

func number64(v any) (float64, bool) {
	switch x := v.(type) {
	case float64:
		return x, true
	case string:
		f, err := strconv.ParseFloat(x, 64)
		return f, err == nil
	}
	return 0, false
}

var mediaWidth = regexp.MustCompile(`\((min|max)-width:\s*(\d+)px\)`)

// widths is a media query's width limits: "(min-width: 1024px)", "(max-width: 767px)", or both.
func widths(q string) (lo, hi int) {
	for _, m := range mediaWidth.FindAllStringSubmatch(q, -1) {
		n, _ := strconv.Atoi(m[2])
		if m[1] == "min" {
			lo = n
		} else {
			hi = n
		}
	}
	return lo, hi
}

// met is whether a condition holds now.
func (cd cond) met(l look) bool {
	switch cd.kind {
	case "state":
		s := l.states[cd.entity].State
		if len(cd.state) > 0 && !contains(cd.state, s) {
			return false
		}
		return !contains(cd.not, s)
	case "numeric_state":
		v, err := strconv.ParseFloat(l.states[cd.entity].State, 64)
		if err != nil {
			return false
		}
		return (cd.above == nil || v > *cd.above) && (cd.below == nil || v < *cd.below)
	case "screen":
		if l.width == 0 {
			return true
		}
		return (cd.minW == 0 || l.width >= cd.minW) && (cd.maxW == 0 || l.width <= cd.maxW)
	case "and":
		return all(cd.subs, l)
	case "or":
		for _, s := range cd.subs {
			if s.met(l) {
				return true
			}
		}
		return len(cd.subs) == 0
	case "not":
		for _, s := range cd.subs {
			if s.met(l) {
				return false
			}
		}
		return true
	}
	return true
}

func all(conds []cond, l look) bool {
	for _, c := range conds {
		if !c.met(l) {
			return false
		}
	}
	return true
}

type condNode struct {
	conds []cond
	child node
}

func (c condNode) blocks(l look) []Block {
	if !all(c.conds, l) {
		return nil
	}
	return c.child.blocks(l)
}

func contains(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

// badges are the chips at the top of a view: a section of tiles here.
func (c *compiler) badges(v any) node {
	items := c.items(v)
	if len(items) == 0 {
		return nil
	}
	return listNode{items: items}
}

var (
	mdLink   = regexp.MustCompile(`\[([^\]]*)\]\([^)]*\)`)
	mdMarks  = regexp.MustCompile(`(\*\*|__|\*|_|~~|` + "`" + `)`)
	mdTags   = regexp.MustCompile(`<[^>]+>`)
	mdPrefix = regexp.MustCompile(`^\s*(#{1,6}\s+|[-*+]\s+|>\s*)`)
)

// plainText is markdown as plain paragraphs: headings, emphasis, links and tags reduced to their
// words, since the page draws text, not HTML.
func plainText(md string) []string {
	var out []string
	for _, line := range strings.Split(md, "\n") {
		line = html.UnescapeString(line)
		line = mdPrefix.ReplaceAllString(line, "")
		line = mdLink.ReplaceAllString(line, "$1")
		line = mdTags.ReplaceAllString(line, "")
		line = mdMarks.ReplaceAllString(line, "")
		line = strings.Join(strings.Fields(line), " ")
		if line != "" {
			out = append(out, line)
		}
	}
	return out
}
